name: Weather Daily Report

on:
  schedule:
    # Runs at 10:15 UTC every day (6:15 AM ET)
    - cron: "15 10 * * *"
  workflow_dispatch:  # Allows manual triggering
  push:
    branches: [main]  # Run on push to main for testing

permissions:
  contents: write  # Allow the workflow to push changes

jobs:
  generate-report:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run weather report generator
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: python run.py
      
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add docs/summary.html output/summary.html data/ || true
          git commit -m "Update weather report - $(date -u +'%Y-%m-%d %H:%M UTC')" || echo "No changes to commit"
          git push || echo "No changes to push"
